import { 
  FaInstagram, 
  FaYoutube, 
  FaTelegram, 
  FaDiscord, 
  FaReddit, 
  FaLinkedin, 
  FaPinterest, 
  FaGamepad, 
  FaRobot, 
  FaGithub,
  FaCertificate,
  FaGraduationCap,
  FaMusic,
  FaFacebook,
  FaDatabase
} from 'react-icons/fa';
import { FaXTwitter } from 'react-icons/fa6';
import {
  SiPixiv,
  SiXdadevelopers,
  SiThreads,
  SiTiktok,
  SiGooglecloud,
  SiGoogle,
  SiOrcid,
  SiKaggle,
  SiGitlab,
  SiSteam,
  SiEpicgames,
  SiBilibili,
  SiXiaomi,
  SiDuolingo
} from 'react-icons/si';
import { TbBrandBluesky, TbWorld } from 'react-icons/tb';
import { MdForum } from 'react-icons/md';
import type { SocialItem, GameItem, PersonalInfo } from './types';

export const personalInfo: PersonalInfo = { 
  alias: 'IRedDragonICY' 
};

export const socials: SocialItem[] = [
  {
    id: 'pixiv',
    name: 'Pixiv',
    href: 'https://www.pixiv.net/en/users/63934020',
    icon: SiPixiv,
    description: 'Illustrations, concepts, and generative art explorations.',
    accent: '#00A2FF',
    gradientFrom: '#00A2FF',
    gradientTo: '#0061FF',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    href: 'https://www.youtube.com/@Ndik',
    icon: FaYoutube,
    description: 'AI demos, research breakdowns, and development logs.',
    accent: '#FF0033',
    gradientFrom: '#FF3D3D',
    gradientTo: '#B31217',
  },
  {
    id: 'hoyolab',
    name: 'HoYoLAB',
    href: 'https://www.hoyolab.com/accountCenter/postList?id=10849915',
    icon: TbWorld,
    description: 'Game logs, posts, and events across HoYoverse titles.',
    accent: '#00D4FF',
    gradientFrom: '#00D4FF',
    gradientTo: '#0077FF',
  },
  {
    id: 'strava',
    name: 'Strava',
    href: 'https://www.strava.com/athletes/164295314',
    icon: TbWorld,
    description: 'Endurance logs, monthly stats, and activity tracking.',
    accent: '#FC4C02',
    gradientFrom: '#FF7A3D',
    gradientTo: '#FC4C02',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    href: 'https://www.instagram.com/ireddragonicy',
    icon: FaInstagram,
    description: 'Daily visuals, behind-the-scenes, and creative snapshots.',
    accent: '#E1306C',
    gradientFrom: '#833AB4',
    gradientTo: '#E1306C',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    href: 'https://www.facebook.com/IRedDragonICY',
    icon: FaFacebook,
    description: 'Community updates, shared posts, and social engagement.',
    accent: '#1877F2',
    gradientFrom: '#1877F2',
    gradientTo: '#0A5AD4',
  },
  {
    id: 'instagram-dev',
    name: 'Instagram (Dev)',
    href: 'https://www.instagram.com/ireddragonicy.code/',
    icon: FaInstagram,
    description: 'Code snippets, dev logs, and engineering snapshots.',
    accent: '#E1306C',
    gradientFrom: '#833AB4',
    gradientTo: '#E1306C',
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    href: 'https://id.pinterest.com/IRedDragonICY/',
    icon: FaPinterest,
    description: 'Moodboards, design references, and visual inspirations.',
    accent: '#BD081C',
    gradientFrom: '#BD081C',
    gradientTo: '#8C0615',
  },
  {
    id: 'x',
    name: 'X (Twitter)',
    href: 'https://x.com/ireddragonicy',
    icon: FaXTwitter,
    description: 'Short updates, threads, and community conversations.',
    accent: '#1DA1F2',
    gradientFrom: '#111111',
    gradientTo: '#2A2A2A',
  },
  {
    id: 'threads',
    name: 'Threads',
    href: 'https://www.threads.net/@ireddragonicy',
    icon: SiThreads,
    description: 'Casual tech notes and quick reflections.',
    accent: '#FFFFFF',
    gradientFrom: '#0A0A0A',
    gradientTo: '#1A1A1A',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    href: 'https://t.me/ireddragonicy',
    icon: FaTelegram,
    description: 'Direct updates and channel broadcasts.',
    accent: '#24A1DE',
    gradientFrom: '#24A1DE',
    gradientTo: '#157EBA',
  },
  {
    id: '4pda',
    name: '4PDA Forum',
    href: 'https://4pda.to/forum/index.php?showuser=7787388',
    icon: MdForum,
    description: 'Discussions, support, and deep‑dive threads with peers.',
    accent: '#1E88E5',
    gradientFrom: '#1E88E5',
    gradientTo: '#1565C0',
  },
  {
    id: 'xda',
    name: 'XDA Developers',
    href: 'https://xdaforums.com/m/hendik-s.9854029/',
    icon: SiXdadevelopers,
    description: 'Development threads and device worklogs.',
    accent: '#EA7100',
    gradientFrom: '#FF8C00',
    gradientTo: '#C75E00',
  },
  {
    id: 'xiaomi-community',
    name: 'Xiaomi Community',
    href: 'https://c.mi.com/id/user/9848f866edb0e8e777c20a5b84a838d4/',
    icon: SiXiaomi,
    description: 'Xiaomi device discussions, tips, and community engagement.',
    accent: '#FF6700',
    gradientFrom: '#FF8C00',
    gradientTo: '#FF6700',
  },
  {
    id: 'discord',
    name: 'Discord',
    href: 'https://discord.com',
    icon: FaDiscord,
    description: 'Handle: @ireddragonicy — reach me via DMs or mentions.',
    accent: '#5865F2',
    gradientFrom: '#5865F2',
    gradientTo: '#3C45A5',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    href: 'https://www.reddit.com/user/IRedDragonICY/',
    icon: FaReddit,
    description: 'Join discussions, share ideas, and explore threads.',
    accent: '#FF4500',
    gradientFrom: '#FF7F50',
    gradientTo: '#FF4500',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    href: 'https://www.tiktok.com/@ireddragonicy',
    icon: SiTiktok,
    description: 'Short-form demos and quick tech experiments.',
    accent: '#FE2C55',
    gradientFrom: '#25F4EE',
    gradientTo: '#FE2C55',
  },
  {
    id: 'bluesky',
    name: 'Bluesky',
    href: 'https://bsky.app/profile/ireddragonicy.bsky.social',
    icon: TbBrandBluesky,
    description: 'Open social updates and research tidbits.',
    accent: '#1185FE',
    gradientFrom: '#0EA5E9',
    gradientTo: '#3B82F6',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    href: 'https://www.linkedin.com/in/ireddragonicy/',
    icon: FaLinkedin,
    description: 'Professional profile, experience, and networking.',
    accent: '#0A66C2',
    gradientFrom: '#0A66C2',
    gradientTo: '#004182',
  },
  {
    id: 'credly',
    name: 'Credly',
    href: 'https://www.credly.com/users/ireddragonicy',
    icon: FaCertificate,
    description: 'Digital badges, certifications, and professional achievements.',
    accent: '#FF8500',
    gradientFrom: '#FF8500',
    gradientTo: '#E5740A',
  },
  {
    id: 'gcloud-skillboost',
    name: 'Google Cloud Skills Boost',
    href: 'https://www.cloudskillsboost.google/public_profiles/a0d99021-862b-40d4-b668-c5a85a2b0f85',
    icon: SiGooglecloud,
    description: 'Badges, labs, and cloud learning progress.',
    accent: '#4285F4',
    gradientFrom: '#34A853',
    gradientTo: '#4285F4',
  },
  {
    id: 'google-developers',
    name: 'Google Developers',
    href: 'https://developers.google.com/profile/u/IRedDragonICY',
    icon: SiGoogle,
    description: 'Developer profile and activities across Google platforms.',
    accent: '#1A73E8',
    gradientFrom: '#34A853',
    gradientTo: '#1A73E8',
  },
  {
    id: 'civitai',
    name: 'CivitAI',
    href: 'https://civitai.com/user/IRedDragonICY',
    icon: FaRobot,
    description: 'Model cards, checkpoints, and generative AI resources.',
    accent: '#00E5A8',
    gradientFrom: '#00E5A8',
    gradientTo: '#00B894',
  },
  {
    id: 'suno',
    name: 'Suno',
    href: 'https://suno.com/@IRedDragonICY',
    icon: FaMusic,
    description: 'AI-generated music creations and audio experiments.',
    accent: '#8B5CF6',
    gradientFrom: '#8B5CF6',
    gradientTo: '#7C3AED',
  },
  {
    id: 'orcid',
    name: 'ORCID',
    href: 'https://orcid.org/0009-0001-4686-1928',
    icon: SiOrcid,
    description: 'Researcher identifier and scholarly record.',
    accent: '#A6CE39',
    gradientFrom: '#A6CE39',
    gradientTo: '#7CB518',
  },
  {
    id: 'datacite',
    name: 'DataCite',
    href: 'https://commons.datacite.org/orcid.org/0009-0001-4686-1928',
    icon: FaDatabase,
    description: 'Research data citations and persistent identifiers.',
    accent: '#F26522',
    gradientFrom: '#F26522',
    gradientTo: '#D14D0F',
  },
  {
    id: 'europepmc',
    name: 'Europe PMC',
    href: 'https://europepmc.org/authors/0009-0001-4686-1928',
    icon: FaGraduationCap,
    description: 'Open access biomedical and life sciences literature.',
    accent: '#2C5F8D',
    gradientFrom: '#2C5F8D',
    gradientTo: '#1A3A5C',
  },
  {
    id: 'academia',
    name: 'Academia.edu',
    href: 'https://universitasahmaddahlan.academia.edu/MohammadFaridHendianto',
    icon: FaGraduationCap,
    description: 'Academic papers, research, and scholarly publications.',
    accent: '#1A472A',
    gradientFrom: '#166534',
    gradientTo: '#15803D',
  },
  {
    id: 'kaggle',
    name: 'Kaggle',
    href: 'https://www.kaggle.com/ireddragonicy',
    icon: SiKaggle,
    description: 'Datasets, notebooks, and competitions.',
    accent: '#20BEFF',
    gradientFrom: '#20BEFF',
    gradientTo: '#0095FF',
  },
  {
    id: 'github',
    name: 'GitHub',
    href: 'https://github.com/IRedDragonICY',
    icon: FaGithub,
    description: 'Open-source projects, code, and contributions.',
    accent: '#FFFFFF',
    gradientFrom: '#0A0A0A',
    gradientTo: '#1A1A1A',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    href: 'https://gitlab.com/IRedDragonICY',
    icon: SiGitlab,
    description: 'Repositories and CI/CD pipelines.',
    accent: '#FC6D26',
    gradientFrom: '#FC6D26',
    gradientTo: '#FCA326',
  },
  {
    id: 'steam',
    name: 'Steam',
    href: 'https://steamcommunity.com/id/IRedDragonICY/',
    icon: SiSteam,
    description: 'Game library, achievements, and community profile.',
    accent: '#00ADEE',
    gradientFrom: '#00ADEE',
    gradientTo: '#1B2838',
  },
  {
    id: 'epic-games',
    name: 'Epic Games',
    href: 'https://store.epicgames.com/u/b3e5802b94574f029852fdf9057f0cad',
    icon: SiEpicgames,
    description: 'Epic account profile and owned titles.',
    accent: '#FFFFFF',
    gradientFrom: '#141414',
    gradientTo: '#2A2A2A',
  },
  {
    id: 'bilibili',
    name: 'Bilibili',
    href: 'https://space.bilibili.com/1604827743',
    icon: SiBilibili,
    description: 'Videos and updates for the CN community.',
    accent: '#00A1D6',
    gradientFrom: '#00A1D6',
    gradientTo: '#0083B0',
  },
  {
    id: 'duolingo',
    name: 'Duolingo',
    href: 'https://www.duolingo.com/profile/ireddragonicy',
    icon: SiDuolingo,
    description: 'Language learning progress and streaks.',
    accent: '#58CC02',
    gradientFrom: '#58CC02',
    gradientTo: '#4B9C0F',
  },
];

export const games: GameItem[] = [
  {
    id: 'zzz',
    name: 'Zenless Zone Zero',
    server: 'Asia',
    uid: '1300928404',
    icon: FaGamepad,
    accent: '#00E5FF',
    gradientFrom: '#00E5FF',
    gradientTo: '#0066FF',
  },
  {
    id: 'mlbb',
    name: 'Mobile Legends',
    server: '-',
    uid: '173772595 (2886)',
    videoSrc: '/icons/mobile_legends.webm',
    accent: '#1DA1F2',
    gradientFrom: '#1DA1F2',
    gradientTo: '#0E7490',
  },
  {
    id: 'arknights',
    name: 'Arknights',
    server: 'Global',
    uid: '43207056',
    icon: FaGamepad,
    accent: '#64748B',
    gradientFrom: '#64748B',
    gradientTo: '#334155',
  },
  {
    id: 'azurlane',
    name: 'Azur Lane',
    server: 'Global',
    uid: '71763639',
    icon: FaGamepad,
    accent: '#38BDF8',
    gradientFrom: '#38BDF8',
    gradientTo: '#0EA5E9',
  },
  {
    id: 'hsr',
    name: 'Honkai: Star Rail',
    server: 'Asia',
    uid: '800754040',
    videoSrc: '/icons/honkai_star_rail.webm',
    accent: '#A855F7',
    gradientFrom: '#7C3AED',
    gradientTo: '#A855F7',
  },
  {
    id: 'genshin',
    name: 'Genshin Impact',
    server: 'Asia',
    uid: '800779666',
    icon: FaGamepad,
    accent: '#F59E0B',
    gradientFrom: '#F59E0B',
    gradientTo: '#D97706',
  },
  {
    id: 'hi3',
    name: 'Honkai Impact 3rd',
    server: 'SEA',
    ign: 'IRedDragonICY',
    icon: FaGamepad,
    accent: '#10B981',
    gradientFrom: '#10B981',
    gradientTo: '#059669',
  },
  {
    id: 'wuthering-waves',
    name: 'Wuthering Waves',
    server: 'SEA',
    uid: '900652876',
    videoSrc: '/icons/wuthering_waves.webm',
    accent: '#22D3EE',
    gradientFrom: '#22D3EE',
    gradientTo: '#0EA5E9',
  },
  {
    id: 'delta-force',
    name: 'Delta Force',
    server: 'Global',
    uid: '54718417559561667570',
    icon: FaGamepad,
    accent: '#FF6B35',
    gradientFrom: '#FF6B35',
    gradientTo: '#D04A02',
  },
];